### ISSUE TITLE
LastAuthority

### ISSUE THREAD

**Issue by JWiersema** [OfficeDev/O365-Win-Connect#1]
This property is never set, hence it remains the empty string. This leads to always having to actively login, never silent. Where and how do you need to set the LastAuthority property

**Comment by jamescro** [comment]
The LastAuthority value is set in the GetTokenHelperAsync method (in AuthenticationHelper.cs). It is stored as a local setting:

_settings.Values["LastAuthority"] = context.Authority;

The getter for the LastAuthority string fetches the value from local settings (see code pasted below).

I'm not reproducing the issue that you report. I can login silently if I quit the app without disconnecting and then run the app again. You do always have to tap the Connect button (since that's what triggers the authentication code), but you shouldn't have to supply credentials again until after disconnecting.

39         private static string LastAuthority 
40         { 
41             get 
42             { 
43                 if (_settings.Values.ContainsKey("LastAuthority") && _settings.Values["LastAuthority"] != null) 
44                 { 
45                     return _settings.Values["LastAuthority"].ToString(); 
46                 } 
47                 else 
48                 { 
49                     return string.Empty; 
50                 } 
51 
 
52             } 
53 
 
54             set 
55             { 
56                 _settings.Values["LastAuthority"] = value; 
57             } 
58         }

**Comment by JWiersema** [comment]
Hi,

Thanks for your quick reply. The error was on my part. Sorry for the trouble!

Kind Regards, jurgen

**Comment by JWiersema** [comment]
Hello Jamescro,

I'd like to ask you why I can add the App with VS2014 to my company's Office365 tenant and authenticate in that way with my company account (that is a normal user). However, the app is then not visible in the Apps section of my company's Azure AD. The App has a client ID and authorization URI in the App.xaml after adding a connected service. How do I properly add the App to my companies Azure AD..?

**Comment by jamescro** [comment]
Your app should be able to query against the _api/search/query REST endpoint if you give it the "Read items in all site collections" permission under "Sites." 

You say that in VS you authenticated as a normal viewer. Did you authenticate to Azure as an admin? Were you able somehow to get an admin's view into AAD?
For more and better expertise in AAD, you should post that part of your question to Stack Overflow, using the "azure-active-directory" tag: http://stackoverflow.com/questions/tagged/azure-active-directory.
